{% set version = "2.2.5" %}

package:
  name: bob.ap
  version: {{ version }}

source:
  fn: bob.ap-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.ap/bob.ap-{{ version }}.zip
  md5: 456d8e76c0818f90f4ba5b1660b87eaf

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - numpy
    - scipy
    - cmake
    - pkg-config

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - numpy
    - scipy

test:
  imports:
    - bob
    - bob.ap

  commands:
    - nosetests -sv bob.ap

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Bob's audio processing utilities

extra:
  recipe-maintainers:
    - 183amir
